src/objects/tmAutoApprovalProfileList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ProfileName__c</fullName>
        <label>Profile Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>tmAutoApprovalProfileList</label>
</CustomObject>

src/objects/tmTrialFeatureRequest__c.object
<CustomObject>
    <description>This object contains trial feature requests created by AEs to provision features to a customer trial.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trial Feature Requests</relationshipLabel>
        <relationshipName>TrialFeatureRequests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AutoApprove__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Approve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Trial Feature Requests</relationshipLabel>
        <relationshipName>TrialFeatureRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Trial Feature Requests</relationshipLabel>
        <relationshipName>TrialFeatureRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Tenant</referenceTo>
        <relationshipLabel>Trial Feature Requests</relationshipLabel>
        <relationshipName>TrialFeatureRequests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialOrderStatus__c</fullName>
        <formula>TEXT(Order__r.Status)</formula>
        <label>Trial Order Status</label>
        <type>Text</type>
        <inlineHelpText> Provisioning status of this request. Activated=Order placed, not provisioned; Pending=Order is in the provisioning queue; Provsioned=the request is complete, and the feature should be available in the trial org.</inlineHelpText>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition</label>
        <length>50</length>
        <type>Text</type>
    </fields>        <fields>
        <fullName>TrialOrderType__c</fullName>
        <label>Trial Order Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Addon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Trial Feature Request</label>
    <nameField>
        <displayFormat>TFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Feature Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/tmTrialFeatureRequestItem__c.object
<CustomObject>
    <description>This object contains list of products and qtys that will be provisioned to a trial</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Trial Feature Request Items</relationshipLabel>
        <relationshipName>TrialFeatureRequestItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedQuantity__c</fullName>
        <label>Requested Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrialFeatureRequest__c</fullName>
        <label>Trial Feature Request</label>
        <referenceTo>tmTrialFeatureRequest__c</referenceTo>
        <relationshipLabel>Trial Feature Request Items</relationshipLabel>
        <relationshipName>TrialFeatureRequestItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProvisionedQuantity__c</fullName>
        <label>Provisioned Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsCoreLicense__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Core License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RequiresApproval__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>    
    <label>Trial Feature Request Items</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trial Feature Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tmDaoTrialFeatureRequest.cls
public with sharing class tmDaoTrialFeatureRequest {
    
    public static tmTrialFeatureRequest__c getTrialFeatureRequestAndItems(Id trialFeatureRequestId) { 
        tmTrialFeatureRequest__c tfr = [SELECT Account__r.BillingCity, Account__r.BillingCountry, Account__r.BillingPostalCode, Account__r.BillingState, Account__r.BillingStreet,
                                        Account__c, Contact__c, Id, Name, Order__c, Status__c, StartDate__c, Tenant__c, TrialOrderStatus__c, CurrencyIsoCode,TrialOrderType__c, Edition__c,AutoApprove__c,
                                            (SELECT Id, Product__c, Product__r.Name, Product__r.Description, Product__r.Eligible_for_Trial__c, Product__r.Admin_Fulfillment__c, Product__r.sfbase__SKU__c, 
                                                RequestedQuantity__c, ProvisionedQuantity__c, IsCoreLicense__c, RequiresApproval__c
                                                FROM TrialFeatureRequestItems__r)
                                        FROM tmTrialFeatureRequest__c 
                                        WHERE Id =: trialFeatureRequestId];
        return tfr;
    }

    public static tmTrialFeatureRequest__c initialize(Account acct, Id tenantId, String edition) {
        //Initialize TFR
        tmTrialFeatureRequest__c tfr = new tmTrialFeatureRequest__c();
        tfr.Account__c = acct.Id;
        tfr.Tenant__c = tenantId;
        tfr.Edition__c = edition;
        tfr.Status__c = tmConstants.TFR_STATUS_DRAFT;
        tfr.StartDate__c = Date.today();
        if (acct.BillingCountry != null) {
            tfr.CurrencyIsoCode = tmDaoProvisioning.getCurrencyCode(acct.BillingCountry);
        }
        return tfr;
    }


    public static List<tmTrialFeatureRequest__c> getFeatureRequestsByAccount(Id accountId) {
        return [select tenant__r.CloudServiceProviderId, tenant__r.ExternalId from tmTrialFeatureRequest__c where account__r.Id = :accountId];
    }

    public static Map<Id, Account> getAccounts(Set<Id> accountIds) {
        Map<Id, Account> accounts = new Map<Id, Account>([
            SELECT Id, BillingCity, BillingCountry, BillingPostalCode, BillingState, BillingStreet, RecordType.Name
            FROM Account
            WHERE id IN :accountIds]);
        return accounts;
    }

    public static String getUserCountry(Id userId) {
        List<User> u = [SELECT Id, ISO_Country__c FROM user WHERE Isactive = true AND Id = :userId];
        if (!u.isEmpty() && !String.isEmpty(u[0].ISO_Country__c)) {
            return u[0].ISO_Country__c;
        } else {
            return '';
        }
    }

    public static Account updateAccount(Account acct) {
        tmDaoTrialFeatureRequestHelper tfrHelper = new tmDaoTrialFeatureRequestHelper();
        return tfrHelper.doUpdateAccountWithoutSharing(acct);
    }

    public static tmTrialFeatureRequest__c save(tmTrialFeatureRequest__c tfr, List<tmTrialFeatureRequestItem__c> tfrItems) {
        tmDaoTrialFeatureRequestHelper tfrHelper = new tmDaoTrialFeatureRequestHelper();
        return tfrHelper.doUpsertTrialFeatureRequestWithoutSharing(tfr, tfrItems);
    }

    public static void deleteItems(List<tmTrialFeatureRequestItem__c> tfrItems) {
        tmDaoTrialFeatureRequestHelper tfrHelper = new tmDaoTrialFeatureRequestHelper();
        tfrHelper.doDeleteTrialFeatureItems(tfrItems);
    }


    private without sharing class tmDaoTrialFeatureRequestHelper {
        public tmTrialFeatureRequest__c doUpsertTrialFeatureRequestWithoutSharing(tmTrialFeatureRequest__c tfr, List<tmTrialFeatureRequestItem__c> tfrItems) {
            tfr.AutoApprove__c = isUserProfileInAutoApprovalList();
            upsert tfr;

            if (tfrItems != null && tfrItems.size() > 0) {
                delete [SELECT Id FROM tmTrialFeatureRequestItem__c WHERE TrialFeatureRequest__c = :tfr.Id];

                for (tmTrialFeatureRequestItem__c tfrItem : tfrItems) {
                    tfrItem.TrialFeatureRequest__c = tfr.Id;
                }
                insert tfrItems;
            }
            return tfr;
        }

        public void doDeleteTrialFeatureItems(List<tmTrialFeatureRequestItem__c> tfrItems) {
            if (tfrItems != null && tfrItems.size() > 0) {
                delete tfrItems;
            }
        }

        public Account doUpdateAccountWithoutSharing(Account acct) {
            Account a = new Account();
            if (acct != null) {
                a.Id = acct.Id;
                a.BillingCountry = acct.BillingCountry;
                if (String.isEmpty(acct.BillingStreet)) {
                    a.BillingStreet = tmConstants.DEFAULT_ACCOUNT_BILLING_STREET;
                }
                if (String.isEmpty(acct.BillingCity)) {
                    a.BillingCity = tmConstants.DEFAULT_ACCOUNT_BILLING_CITY;
                }                
                if (String.isEmpty(acct.BillingState)) {
                    a.BillingState = tmConstants.DEFAULT_ACCOUNT_BILLING_STATE;
                }
                if (String.isEmpty(acct.BillingPostalCode)) {
                    a.BillingPostalCode = tmConstants.DEFAULT_ACCOUNT_BILLING_ZIP;
                }
                update a;
            }
            return a;
        }

        private boolean isUserProfileInAutoApprovalList() {
            String profileName = [Select Id, Name from Profile where Id =  :UserInfo.getprofileId()] .Name;
            for(tmAutoApprovalProfileList__c tmAprovalProfile : tmAutoApprovalProfileList__c.getall().values()) {
                if(profileName == tmAprovalProfile.ProfileName__c){
                    return true;
                }
            }
            return  false;
        }
    }
}